# Generated by Django 5.0.3 on 2024-03-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_produks_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='produks',
            name='descriptiondua',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produks',
            name='fitur',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produks',
            name='subtitle',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produks',
            name='ukuran',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produks',
            name='warna',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
